name=MightyOhmGeigerCounter
version=1.1.0
author=Tyler Nielsen <tylernielsenn@gmail.com>
maintainer=Tyler Nielsen <tylernielsenn@gmail.com>
sentence=Arduino library for the Mighty Ohm Geiger Counter.
paragraph=This library interfaces with the "pulse" output of the geiger counter using interrupts, allowing for easy reading from the geiger counter without using the its serial interface. 
category=Sensors
url=https://github.com/SnailDragon/MightyOhmGeigerCounter
architectures=*
includes=GeigerCounter.h
